name: chempred
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - black
  - flake8
  - imbalanced-learn
  - isort
  - lightgbm
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - py-xgboost
  - rdkit
  - scikit-learn
  - scikit-mol
  - tqdm
  - pip:
    - mkdocs